services:
  pg:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: clair
      POSTGRES_USER: clair
      POSTGRES_DB: clair
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U clair"]
      interval: 5s
      retries: 20
    restart: unless-stopped

  # Local Docker registry with TLS (5000 inside, 5001 on host)
  registry:
    image: registry:2
    ports: ["5001:5000"]
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/tls.crt
      REGISTRY_HTTP_TLS_KEY: /certs/tls.key
    volumes:
      - ../certs:/certs:ro
      - regdata:/var/lib/registry
    restart: unless-stopped

  clair:
    image: quay.io/projectquay/clair:4.8.0
    depends_on:
      pg: { condition: service_healthy }
      registry: { condition: service_started }
    environment:
      CLAIR_MODE: combo
      CLAIR_CONF: /etc/clair/config.yaml
      SSL_CERT_FILE: /usr/local/share/ca-certificates/local-registry-ca.crt
    volumes:
      - ./config.yaml:/etc/clair/config.yaml:ro
      - ../certs/ca.crt:/usr/local/share/ca-certificates/local-registry-ca.crt:ro
    ports:
      - "6060:6060"
      - "6061:6061"
    restart: unless-stopped

volumes:
  regdata: {}